name: tea
description: "A new Flutter project."
 
 
publish_to: 'none'  

 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.2.1
  http: ^1.5.0
#  intl: ^0.20.2
  intl: ^0.18.1

  logger: ^2.5.0
  url_launcher: ^6.3.1
  connectivity_plus: ^5.0.1
  carousel_slider: ^5.1.1
  iconsax_flutter: ^1.0.1
  get: ^4.7.2
  get_storage: ^2.1.1
  lottie: ^3.3.2
  shimmer: ^3.0.0
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.2.1
  android_alarm_manager_plus: ^5.0.0
  share_plus: ^7.2.1
  path_provider: ^2.1.2
#  flutter_local_notifications: ^17.1.2
  flutter_local_notifications: ^17.2.4
  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.8
#  timezone: ^0.9.3
  timezone: ^0.9.0
  flutter_timezone: ^5.0.1
#  awesome_notifications: ^0.10.1
  awesome_notifications: ^0.7.4+1

  rename: ^3.1.0

#  flutter_native_timezone: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true


  assets:
    - assets/logo/
    - assets/images/
    - assets/icons/brands/
    - assets/images/profile/
    - assets/images/dashboard/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/icons/payment_methods/
    - assets/images/products/
    - assets/images/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/paypal.png
    - assets/images/animations/task.json

   
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
